# GitHub Action that uses Black to reformat the Python code in an incoming pull request.
# If all Python code in the pull request is compliant with Black then this Action does nothing.
# Othewrwise, we fail and prevent a merge.
# https://github.com/cclauss/autoblack

name: autoblack
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Install Black
        run: pip install black
      - name: Run black --check .
        run: black --check .
